### ISSUE TITLE
硬件询问

### ISSUE THREAD

**Issue by dbxz** [vimar-gu/MSINet#11]
作者大大可以告诉我论文模型运行在什么硬件上吗

**Comment by vimar-gu** [comment]
你好～ 行人数据集在2080Ti上就可以跑起来，车辆数据集可能需要V100

**Comment by dbxz** [comment]
谢谢作者大大，作者大大可以发我VehicleId的解压密码吗，数据集作者光给我压缩包，没给我发压缩密码

**Comment by vimar-gu** [comment]
不好意思回复晚了，只编辑的话我不会收到通知，请问现在还需要吗？

**Comment by dbxz** [comment]
要的要的大佬，数据集作者到现在还没回我

**Comment by dbxz** [comment]
> 不好意思回复晚了，只编辑的话我不会收到通知，请问现在还需要吗？

要的要的大佬，数据集作者回复确实有点慢

**Comment by vimar-gu** [comment]
请问你可以提供一个邮箱吗？

**Comment by dbxz** [comment]
> 请问你可以提供一个邮箱吗？

18711145623@163.com谢谢大佬！
