### ISSUE TITLE
如何将模型转成onnx

### ISSUE THREAD

**Issue by hjl0202** [vimar-gu/MSINet#12]

**Comment by vimar-gu** [comment]
不好意思，我没有这方面的经验，不过转成onnx的话想必可以参考一下别的例子？

**Comment by hjl0202** [comment]
是否有训练好的模型下载路径，如何验证自己的数据

**Comment by vimar-gu** [comment]
在README里面有ImageNet预训练模型的下载路径，验证自己的数据只需要参考`market1501.py`等文件写相应的数据加载脚本即可
