### ISSUE TITLE
If a private dataset is used for training, how should the pre-training data be obtained?

### ISSUE THREAD

**Issue by demons0107** [vimar-gu/MSINet#2]

**Comment by vimar-gu** [comment]
The pre-training process is conducted on the ImageNet dataset. So for any Re-ID datasets, the provided pre-trained model is generally practical.

**Comment by demons0107** [comment]
Thank you very much for your answer！ I would like to know how the data from the pretrained folder is obtained, is the data obtained after training resnet50 pre-trained by imagenet?

**Comment by vimar-gu** [comment]
I'm not sure what do you indicate by "data from the pretrained folder". 
If you mean the pretrained model, it is the MSINet network weights trained on the ImageNet.

**Comment by demons0107** [comment]
I'm very sorry for my misunderstanding. Thank you very much for your answer!
