### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by Divine0719** [vimar-gu/MSINet#3]
I tried python train.py --pretrained with Market-1501-v15.09.15, but it came up with error in comput 'feats'
![微信截图_20230415141606](https://user-images.githubusercontent.com/77132276/232190044-ab9b686a-2bb1-4100-a5eb-eab439420576.png)

here is the Traceback

  File "E:\ReID\MSINet\train.py", line 107, in <module>
    main(args)
  File "E:\ReID\MSINet\train.py", line 53, in main
    do_train(args, model, criterion, train_loader, test_loader,
  File "E:\ReID\MSINet\reid\engine\trainer.py", line 59, in do_train
    cmc, mAP, _, _, _, _, _ = evaluator.compute()
  File "E:\ReID\MSINet\reid\utils\metrics.py", line 110, in compute
    feats = torch.cat(self.feats, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

Many thx!

**Comment by vimar-gu** [comment]
Hi, it seems that the dataset is not succesfully loaded. Please check the path of the dataset~

**Comment by Divine0719** [comment]
> 
Thx a lot , problem has been solved.
I mistook the reid/data as the ./data

Thx again for answering~
