### ISSUE TITLE
IDM+MSINet代码咨询

### ISSUE THREAD

**Issue by wangtaos** [vimar-gu/MSINet#4]
尊敬的作者您好：
       我看您实验中有将IDM与MSINet进行一个结合，但是我自己尝试将这两者进行结合后发现达不到您论文上的精度，您方便提供一下IDM+MSINet的相关代码吗？

**Comment by vimar-gu** [comment]
Hi，请问下你是用什么硬件配置做的实验呢？加上MSINet之后可以达到一个什么样的精度？

**Comment by wangtaos** [comment]
> 

显卡是特斯拉 A100 40G，然后精度M-MS的话 mAP只能到35%，达不到论文中的37.8%，您可以把你相关代码给我看一下吗，我保证不外传。

**Comment by vimar-gu** [comment]
请问是用4卡跑的还是1卡跑的呢？之前我跑这个实验的服务器我已经没有权限使用了，我这两天重新在IDM上面跑一下结果~

**Comment by wangtaos** [comment]
> 请问是用4卡跑的还是1卡跑的呢？之前我跑这个实验的服务器我已经没有权限使用了，我这两天重新在IDM上面跑一下结果~

4卡和1卡都试过，但结果都不理想

**Comment by vimar-gu** [comment]
Hi，不好意思最近比较忙，我复现了一下结果，你可以给我一个邮箱吗？我把代码和log一起发给你

**Comment by wangtaos** [comment]
> 

真的非常感谢您！！！，邮箱：1943405014@qq.com

**Comment by wangtaos** [comment]
> Hi，不好意思最近比较忙，我复现了一下结果，你可以给我一个邮箱吗？我把代码和log一起发给你
真的非常感谢您！！！，邮箱：[1943405014@qq.com](mailto:1943405014@qq.com)
