### ISSUE TITLE
AssertionError: Error: all query identities do not appear in gallery RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 256 but got size 64 for tensor number 1 in the list. 

### ISSUE THREAD

**Issue by Chungcheukting** [vimar-gu/MSINet#5]
hello您好，我想复现VID的MSINet和MSINet-SAM部分 SAM部分的命令行如下python train.py --pretrained --logs-dir './logs_sam' --sam-mode pos_neg 报错RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 256 but got size 64 for tensor number 1 in the list. 以及MSINet部分命令行如下 python train.py --pretrained 报错AssertionError: Error: all query identities do not appear in gallery 看到metrics.py代码里有如下remove部分# remove gallery samples that have the same pid and camid with query
        order = indices[q_idx]  # select one row
        remove = (g_pids[order] == q_pid) & (g_camids[order] == q_camid)
        keep = np.invert(remove) 不知道为什么仍然报错 希望得到您的帮助！十分感谢！

**Comment by vimar-gu** [comment]
Hi，不好意思前段时间因为有事回复迟了
第一个报错可能是将 msinet.py 111 行改为 (16, 16)
第二个报错是因为 vehicleid 数据集只有 1 个 camera id，因此需要将 metric.py 60 行后面那个 [keep] 注释掉

**Comment by Chungcheukting** [comment]
谢谢您！已解决！
