### ISSUE TITLE
veri数据集训练相关问题

### ISSUE THREAD

**Issue by moonstarL** [vimar-gu/MSINet#8]
下载开源的预训练权重，训练Market1501数据集，得到训练和测试结果与您论文中结果一致。
但是使该权重训练veri数据集，得到的结果与论文差异较大,尤其是mAP值。
请问可能是哪些问题导致的呢？训练Market1501与veri数据集加载的是相同的预训练权重吗？

The test feature is normalized
=> Computing DistMat with euclidean distance
Validation Results - Epoch[299]
mAP: 46.6%
CMC curve, Rank-1  :80.9%
CMC curve, Rank-5  :88.9%
CMC curve, Rank-10 :91.8%

**Comment by vimar-gu** [comment]
Hi，请问你们加了参数 --width 256 吗？

**Comment by sunrabbbit** [comment]
同样使用下载的预训练权重 运行python train.py -ds veri --pretrained --width 256。模型在40epoch时loss已经不再下降，Validation Results - Epoch[39]
mAP: 52.4%
CMC curve, Rank-1  :87.5%
同时附上训练log
[log_2311202152.txt](https://github.com/vimar-gu/MSINet/files/13415817/log_2311202152.txt)

**Comment by vimar-gu** [comment]
您好，loss不再下降一方面不代表已经到达最优性能，另一方面后续还会降学习率loss还会继续下降。

实验设置一共需要跑350 epoch，可以等跑完了再看下能否复现性能~

**Comment by sunrabbbit** [comment]
感谢指点

**Comment by giraffeooo** [comment]
> 感谢指点

您好，请问您复现出来结果了吗？我用其他的数据集跑出来效果也不太理想。除了增大epoch还需要调整其他参数吗？

**Comment by vimar-gu** [comment]
应该不需要了，可以把你的训练log贴一下吗？我可以看看有没有什么问题

**Comment by giraffeooo** [comment]
> 应该不需要了，可以把你的训练log贴一下吗？我可以看看有没有什么问题

谢谢，我微调了lr和momentum，结果好多了

**Comment by DLzeroo** [comment]
> > 应该不需要了，可以把你的训练log贴一下吗？我可以看看有没有什么问题
> 
> 谢谢，我微调了lr和momentum，结果好多了

您好，请问您有没有测试在VehicleID上的效果吗？如果有的话，可否告知一下微调的具体数值呢？另外，您在veri数据集上的微调具体数值可否一并告知，万分感谢！！！
