### ISSUE TITLE
请问能否发布车辆跨域pretrained模型

### ISSUE THREAD

**Issue by YsasaGb** [vimar-gu/MSINet#9]
readme中的预训练模型链接似乎是错的

**Comment by vimar-gu** [comment]
您好，感谢对这个工作的关注。

readme中的模型是在msmt数据集上搜索得到的结构，并在ImageNet上进行pre-train。

这个模型对行人和车辆的数据都是通用的。如果要应用到车辆跨域任务上的话，可以在这个pre-trained模型的基础上用车辆数据集（如 VehicleID）进行fine-tune。

**Comment by YsasaGb** [comment]
您好，readme文件给出的google driver链接中似乎没有预训练的.pth文件

**Comment by vimar-gu** [comment]
google drive 有一个对 tar 压缩包的预览，直接点击右上角的下载就可以了

**Comment by YsasaGb** [comment]
感谢回复，已解决

**Comment by vimar-gu** [comment]
不客气！
